### ISSUE TITLE
Unnecessary folding of method use for methods starting with word  'issue'.

### ISSUE THREAD

**Issue by lukasz-kaminski** [cheptsov/AdvancedExpressionFolding#90]
I implemented and used method `issueCertificate()`.
I guess the plugin thought it was a getter for some boolean and this line:

```
Certificate certificate = issueCertificate();
```

got folded to:

```
Certificate certificate = sueCertificate;
```

Probably a check for camelCase after prefix `is` would be sufficient.

It's not a big problem but it's annoying :)

**Comment by mibac138** [comment]
Related #24

**Comment by cheptsov** [comment]
I tried to reproduce with 0.9.9.4 and it seems to be gone. Please check and confirm.

**Comment by jfcabral** [comment]
Hey @cheptsov I've just confirmed this behaviour still happens in v0.9.9.4 😕 
I've submitted PR #92 to specifically correct this issue. Still, I've noticed that since I did other commits in the meanwhile, they were all appearing in that PR (which was not my intention), so I moved the other commits into a branch.
Do you think you could check PR #92? If you have any suggestion or feedback do not hesitate to contact me.
Cheers
